version: '2'

services:
  postgres:
    container_name: lemmoney-postgres
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'lemmoney'